# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2eb8d18c96ec70d3495f4f151eed303a72d60733a09f248b3ff6d3ebbefbb80ab9b17d1fd685b03c765b9aa42f5f6635a4565ffe8ddec54a84784ed4efa2e3ff

test:
  secret_key_base: 0d31034f19b20da896c90b2b319b0be1771fc4f13f5e5e4f153ea55a7fcf390a212e2e7f3af8b3ac5c91b4cc5f6a6511b855c68a591076ad47a55f46eac3c6f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
